version: '3.3'
services:
  web:
    # image: php:7.3-apache
    build:
      context: ./php_files
      dockerfile: Dockerfile
    container_name: php73
    volumes:
      - ./php_files:/var/www/html/
    ports:
      - "8006:80"
