version: '3.3'
services:
  web:
    # image: php:7.3-apache
    build:
      context: ./php_files
      dockerfile: Dockerfile
    container_name: php73
    depends_on:
      - db
    volumes:
      - ./php_files:/var/www/html/
    ports:
      - "8006:80"
  db:
    container_name: mysql_8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: demo
      MYSQL_DATABASE: demo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: demo
    ports:
      - "6033:3306"